export const products = [
  {
    id: 1,
    title: "Mentalidad Mamba",
    price: 6000,
    stock: 2,
    description: "Un libro..A",
    author: "Kobe Bryant",
    categorie: "Psicología Deportiva",
    image:
      "https://res.cloudinary.com/dlqijmifn/image/upload/v1686234671/BooksSale/deporte02_fixfqc.png",
  },
  {
    id: 2,
    title: "Once anillos",
    price: 7500,
    stock: 3,
    description: "Un libro..B",
    author: "Phil Jackson",
    categorie: "Psicología Deportiva",
    image:
      "https://res.cloudinary.com/dlqijmifn/image/upload/v1686234671/BooksSale/deporte03_ov5czn.png",
  },
  {
    id: 3,
    title: "The quality of madness",
    price: 9000,
    stock: 4,
    description: "Un libro..C",
    author: "Tim Rich",
    categorie: "Psicología Deportiva",
    image:
      "https://res.cloudinary.com/dlqijmifn/image/upload/v1686234671/BooksSale/deporte05_hyjwnq.png",
  },
  {
    id: 4,
    title: "Un viaje al interior",
    price: 8500,
    stock: 2,
    description: "Un libro..D",
    author: "Sergio Cachito Vigil",
    categorie: "Psicología Deportiva",
    image:
      "https://res.cloudinary.com/dlqijmifn/image/upload/v1686234671/BooksSale/deporte01_at1jli.png",
  },
  {
    id: 5,
    title: "Viento",
    price: 4500,
    stock: 7,
    description: "Un libro..E",
    author: "Santiago Lange",
    categorie: "Psicología Deportiva",
    image:
      "https://res.cloudinary.com/dlqijmifn/image/upload/v1686234670/BooksSale/deporte04_lqda4t.png",
  },
  {
    id: 6,
    title: "Titanes",
    price: 7600,
    stock: 8,
    description: "Un libro..F",
    author: "Tim Ferris",
    categorie: "Desarrollo Personal",
    image:
      "https://res.cloudinary.com/dlqijmifn/image/upload/v1686234758/BooksSale/desarrollo06_v51oxa.png",
  },
  {
    id: 7,
    title: "Cartas morales a Lucilio",
    price: 9000,
    stock: 10,
    description: "Un libro..G",
    author: "Séneca",
    categorie: "Desarrollo Personal",
    image:
      "https://res.cloudinary.com/dlqijmifn/image/upload/v1686234758/BooksSale/desarrollo05_dpgza8.png",
  },
  {
    id: 8,
    title: "El poder de los hábitos",
    price: 4500,
    stock: 7,
    description: "Un libro..H",
    author: "Charles Duhigg",
    categorie: "Desarrollo Personal",
    image:
      "https://res.cloudinary.com/dlqijmifn/image/upload/v1686234709/BooksSale/desarrollo02_juagho.png",
  },
  {
    id: 9,
    title: "El manual de Epicteto",
    price: 4000,
    stock: 3,
    description: "Un libro..I",
    author: "Epicteto",
    categorie: "Desarrollo Personal",
    image:
      "https://res.cloudinary.com/dlqijmifn/image/upload/v1686234708/BooksSale/desarrollo01_vkotc4.png",
  },
  {
    id: 10,
    title: "El señor de los Anillos - I ",
    price: 7000,
    stock: 5,
    description: "Un libro..J",
    author: "JR Tolkien",
    categorie: "Aventura",
    image:
      "https://res.cloudinary.com/dlqijmifn/image/upload/v1686234690/BooksSale/Aventura01_krxpj7.png",
  },
  {
    id: 11,
    title: "El señor de los Anillos - II ",
    price: 7000,
    stock: 4,
    description: "Un libro..K",
    author: "JR Tolkien",
    categorie: "Aventura",
    image:
      "https://res.cloudinary.com/dlqijmifn/image/upload/v1686234690/BooksSale/aventura02_tsbaof.png",
  },
  {
    id: 12,
    title: "El señor de los Anillos - III",
    price: 7000,
    stock: 5,
    description: "Un libro..L",
    author: "JR Tolkien",
    categorie: "Aventura",
    image:
      "https://res.cloudinary.com/dlqijmifn/image/upload/v1686234690/BooksSale/aventura03_cxf6vu.png",
  },
  {
    id: 13,
    title: "Un mago de terramar - I",
    price: 6000,
    stock: 11,
    description: "Un libro..M",
    author: "Ursula K. Leguin",
    categorie: "Aventura",
    image:
      "https://res.cloudinary.com/dlqijmifn/image/upload/v1686234708/BooksSale/aventura04_isi4zg.png",
  },
  {
    id: 14,
    title: "Un mago de terramar - II",
    price: 7000,
    stock: 5,
    description: "Un libro..N",
    author: "Ursula K. Leguin",
    categorie: "Aventura",
    image:
      "https://res.cloudinary.com/dlqijmifn/image/upload/v1686234708/BooksSale/aventura05_ps2wpv.png",
  },
  {
    id: 15,
    title: "Un mago de terramar - III",
    price: 7500,
    stock: 2,
    description: "Un libro..O",
    author: "Ursula K. Leguin",
    categorie: "Aventura",
    image:
      "https://res.cloudinary.com/dlqijmifn/image/upload/v1686234708/BooksSale/aventura06_uc0vkw.png",
  },
  {
    id: 16,
    title: "Un mago de terramar - IV",
    price: 7000,
    stock: 5,
    description: "Un libro..P",
    author: "Ursula K. Leguin",
    categorie: "Aventura",
    image:
      "https://res.cloudinary.com/dlqijmifn/image/upload/v1686234708/BooksSale/aventura07_nhwoge.png",
  },
  {
    id: 17,
    title: "El inversor Inteligente",
    price: 11000,
    stock: 3,
    description: "Un libro..R",
    author: "Benjamin Graham",
    categorie: "Finanza Personal",
    image:
      "https://res.cloudinary.com/dlqijmifn/image/upload/v1686234690/BooksSale/inversion01_zpnf9e.png",
  },
  {
    id: 18,
    title: "Código dinero",
    price: 7000,
    stock: 5,
    description: "Un libro..P",
    author: "Raimon Samsó",
    categorie: "Finanza Personal",
    image:
      "https://res.cloudinary.com/dlqijmifn/image/upload/v1686234690/BooksSale/inversion02_fbvvys.png",
  },
  {
    id: 19,
    title: "Los secretos de la Mente Millonaria",
    price: 7000,
    stock: 9,
    description: "Un libro..S",
    author: "T Harv Eker",
    categorie: "Finanza Personal",
    image:
      "https://res.cloudinary.com/dlqijmifn/image/upload/v1686234690/BooksSale/inversion03_xqtpm3.png",
  },
  {
    id: 20,
    title: "Padre rico, padre pobre",
    price: 7000,
    stock: 5,
    description: "Un libro..T",
    author: "Robert Kiyosaki",
    categorie: "Finanza Personal",
    image:
      "https://res.cloudinary.com/dlqijmifn/image/upload/v1686234708/BooksSale/inversion04_jqpv31.png",
  },
  {
    id: 21,
    title: "La bolsa o la vida",
    price: 8500,
    stock: 12,
    description: "Un libro..U",
    author: "Vicki Robin",
    categorie: "Finanza Personal",
    image:
      "https://res.cloudinary.com/dlqijmifn/image/upload/v1686234708/BooksSale/inversion05_q4ypeu.png",
  },
];
